<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.sbp.gazii.podelki</groupId>
        <artifactId>gaz-podelki-dependencies</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>gaz-podelki-queue</artifactId>
    <version>1.0.0</version>

    <dependencies>
        <!-- Spring Boot Autoconfigure -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
            <!-- Версия управляется через BOM в родительском pom -->
        </dependency>

        <!-- Spring Context (обычно нужен для autoconfigure) -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
    </dependencies>
</project>